name: "Issue Branch"
description: "Create a branch"
inputs:
  branch:
    description: "Brnach name."
    required: true
  sha:
    description: "SHA."
    required: false
  repository:
    description: "The owner/repo that the branch will get created."
    required: false
outputs:
  created:
    description: "String value, 'false': branch exists, 'true': branch created."
runs:
  using: "node20"
  main: "dist/index.js"
